# This is a basic workflow to help you get started with Actions

name: Staging - CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
        branches:
            - beta
            - alpha
            - next
    pull_request:
        branches:
            - beta
            - alpha
            - next

env:
    GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
    GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
    GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
    GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        name: Starting Build

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: '14'

            # Runs a single command using the runners shell
            - name: Installing dependencies via npm install
              run: npm install

            - name: Semantic Release
              id: semantic
              uses: codfish/semantic-release-action@master
              # if: github.event_name == 'push'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - run: echo "$OUTPUTS"
              env:
                  OUTPUTS: ${{ toJson(steps.semantic.outputs) }}
